[package]
name = "tiktoken-cli"
version = "0.1.0"
edition = "2021"

[dependencies]
tiktoken-rs = { git = "https://github.com/zurawiki/tiktoken-rs" }
clap = { version = "4.5", features = ["derive"] }
serde = { version = "1.0", features = ["derive"] }
anyhow = "1.0"
